[package]
name = "rust_game"
version = "0.1.0"
authors = ["Sean Jones <seanjones2848@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.sdl2]
version = "0.34.4"
default-features = false
features = ["image"]
